### PR TITLE
Added Travis CI support

### PR DESCRIPTION
**Pull request by paweldudek**
As discussed in https://github.com/specta/specta/issues/125 I've added Travis CI support. 

#### What changed? 

I've taken a different approach than @robb in https://github.com/specta/specta/pull/81. Rather than dropping in script package I've extended existing Rakefile with testing tasks. Ask you can see in build [here](https://travis-ci.org/paweldudek/specta) everything seems to working just well!

### CODE REVIEW

**Comment by paweldudek** [comment]
Boom, we're green! :tada:

**Comment by robb** [comment]
:boom:

**Comment by orta** [comment]
Hey, awesome work @paweldudek !

**Comment by orta** [comment]
this is interesting - master is running additional tests which include sequence tests which are failing, https://travis-ci.org/specta/specta/builds/50258272

**Pull request merged**
