### PR TITLE
add new DSL named check_dealloc

### PR DESCRIPTION
**Pull request by WilliamZang**
it's parameter is an obj, and it will assert when the obj doesn't dealloc.
But I've no idea. How to add an unit test for this feature.Does anyone can help me?

### CODE REVIEW

**Comment by orta** [comment]
I'm not sure about this, Spectra's responsibilities are to provide a structure for the tests and projects like [expecta](https://github.com/specta/expecta) offer matchers separately. This de-clarifys the feature-set in a way I'm not sold on. Anyone else got opinions?

**Comment by WilliamZang** [comment]
Such as waitUntil it's a feature of specta. I think it's a structure. The better way to implement this feature is in specta, I need put all the spec in a block and check the objects.

**Comment by paweldudek** [comment]
I agree with @orta on this one, Specta's supposed to provide DSL for BDD-like tests. Nothing more. 

Expecta's responsibility is to provide set of assertions for, well, asserting whether certain behaviour occurred. 

This feels like a specific matcher that leaked into Spectas internal architecture, especially this method: 

```objc
- (void)spt_checkThis:(id)obj {
  SPTCheckerObj *checkObj = [SPTCheckerObj new];
  checkObj.obj = obj;
  checkObj.checkBlock = ^(id checkingObj) {
    XCTAssertNil(checkingObj);
  };
  @synchronized(self.checkerObjs) {
    [self.checkerObjs addObject:checkObj];
  }
}
```

as it actually contains a matcher (which should be a part of Expecta). Perhaps it is possible to extend Specta to provide sort of generic interface which Expecta could use and that would solve your problem?

Also, personally I just write a test that contains an `@autorelease` and a `__weak` variable before it and then just use Expecta to check whether object has been released. It's a bit longer but it does the trick :wink:

**Comment by WilliamZang** [comment]
Shall I add this feature into Expecta with some support interface in Specta?

**Comment by orta** [comment]
@WilliamZang as long as it's pretty generic in Specta, sure :+1:

**Comment by orta** [comment]
Closing due to inactivity :+1: feel free to re-open.

**Pull request closed without merging**
